apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: sum-and-multiply-pipeline
spec:
  tasks:
  - name: say-hello
    taskSpec:
      steps:
        - name: echo
          image: alpine
          script: |
            #!/bin/sh
            echo "Hello, World!"
            sleep 30
  - name: say-goodbye
    runAfter:
    - say-hello
    taskSpec:
      steps:
        - name: echo
          image: alpine
          script: |
            #!/bin/sh
            echo "Goodbye, World!"


