apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "piplinerun1-remote-annotations"
  annotations:
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/task-1: "https://github.com/openshift-pipelines/pipelines-as-code/blob/main/pkg/pipelineascode/testdata/pull_request/.tekton/task.yaml"
spec:
  pipelineRef:
    name: pipeline1-in-tekton-dir