---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: another-pr-pac-demo
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[refs/heads/*]"
    pipelinesascode.tekton.dev/on-comment: "^/backport"
    #pipelinesascode.tekton.dev/on-comment: "savita"
    # pipelinesascode.tekton.dev/on-comment: "hello-world"
    #pipelinesascode.tekton.dev/on-cel-expression: |
      #files.renamed.exists(x, x.matches('components/'))
    # pipelinesascode.tekton.dev/on-target-branch: "[refs/heads/*]" 
    # pipelinesascode.tekton.dev/task: "git-clone"
    # How many runs we want to keep.
    # pipelinesascode.tekton.dev/max-keep-runs: "7"
    # pipelinesascode.tekton.dev/on-cel-expression: | event == "push" && target_branch == "[refs/heads/*]" && "staging/*".pathChanged()
       # event_title.startsWith("Merge pull request") "docs/*.md".pathChanged() "components/?*/base/**".pathChanged()
       # event == "pull_request" && target_branch == "refs/heads/*" && ("**/staging/**".pathChanged())
       # event == "pull_request" && target_branch == "main" && source_branch == "refs/heads/*"  && ("staging/?*/base/**".pathChanged() || "staging/*".pathChanged() || "/staging/**".pathChanged())
       # event == "push" && target_branch == "main" && source_branch == "refs/heads/*"  && ("staging/?*/base/**".pathChanged() || "staging/*".pathChanged() || "*/staging/**".pathChanged())
       # ( target_branch == "refs/heads/*" && event == "push" && ("components/**".pathChanged()) )
    # pipelinesascode.tekton.dev/on-cel-expression: |
      # ( event == "push" && source_branch == "refs/heads/*" ) && "components/?*/base/**".pathChanged()
      # value=$(echo "$a" | awk -F'[/ ]' '{print $2}')
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: pull_request_number
      value: "{{ pull_request_number }}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
      - name: pull_request_number
    tasks:
      - name: noop-task
        taskSpec:
          steps:
            - name: noop-task
              image: registry.access.redhat.com/ubi9/go-toolset:1.20
              script: |
                echo "printing all the values here"
                echo {{ trigger_comment }}
                echo {{ pull_request_number }}
                echo {{ repo_url }}
                echo {{ revision }}
                prNumber="{{ pull_request_number }}"
                a="{{ trigger_comment }}"
                echo "what are the values****"
                echo $a
                echo $prNumber
                echo "end of the values****"
                value=$(echo "$a" | awk '{print $2}')
                echo "********************"
                echo $value
                echo "********************"
                git clone {{ repo_url }}
                cd {{ repo_name }}
                ls -lrt
                git config --global user.email "sashture@redhat.com"
                git config --global user.name "savitaashture"
                git fetch origin pull/$prNumber/head:$prNumber
                git checkout $value
                git merge $prNumber
                echo "there is a fail in push"
                echo "git push origin $value"
                git remote set-url origin https://savitaashture:c8978ebcd5407637a6da1c8d178654267fd66c1f@github.com/{{ repo_owner }}/{{ repo_name }}.git
                git remote -v
                git push origin $value



