apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: helloworld-testing-
  annotations:
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "master"
spec:
  pipelineSpec:
    tasks:
      - name: echo-hello
        taskSpec:
          steps:
            - name: echo
              image: registry.access.redhat.com/ubi9/ubi-micro
              env:
                - name: HOME
                  value: $(workspaces.source.path)
              script: |
                #!/usr/bin/env bash
                echo "hello world"
  serviceAccountName: pipeline
