---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: another-pr-pac-demo
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    # pipelinesascode.tekton.dev/on-event: "[incoming]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/pipeline: "[buildpacks]"
    # pipelinesascode.tekton.dev/on-target-branch: "[refs/heads/*]" 
    pipelinesascode.tekton.dev/task: "[git-clone, buildpacks, buildpacks-phases]"
    # How many runs we want to keep.
    # pipelinesascode.tekton.dev/max-keep-runs: "2"
    # pipelinesascode.tekton.dev/on-cel-expression: | event == "push" && target_branch == "[refs/heads/*]" && "staging/*".pathChanged()
       # event_title.startsWith("Merge pull request") "docs/*.md".pathChanged()
spec:
  pipelineRef:
    name: buildpacks
