---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: kanikotest
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: "git-clone"
    pipelinesascode.tekton.dev/task: "kaniko"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: image
      value: quay.io/savitaashture/kaniko-chains
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
      - name: image
    workspaces:
      - name: source
      - name: basic-auth
      - name: dockerconfig
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
          kind: ClusterTask
        workspaces:
          - name: output
            workspace: source
          - name: basic-auth
            workspace: basic-auth
        params:
          - name: url
            value: $(params.repo_url)
          - name: revision
            value: $(params.revision)
      - name: kaniko-test
        taskRef:
          name: kaniko
        runAfter:
        - fetch-repository
        workspaces:
          - name: source
            workspace: source
          # - name: basic-auth
          #   workspace: basic-auth
          - name: dockerconfig
            workspace: dockerconfig
        params:
          - name: IMAGE
            value: $(params.image)
          # - name: EXTRA_ARGS
          #   value:
          #     - --skip-tls-verify
      - name: noop-task
        runAfter:
          - fetch-repository
        workspaces:
          - name: source
            workspace: source
        taskSpec:
          workspaces:
            - name: source
          steps:
            - name: noop-task
              image: registry.access.redhat.com/ubi9/ubi-micro
              workingDir: $(workspaces.source.path)
              script: |
                exit 0
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  # This workspace will inject secret to help the git-clone task to be able to
  # checkout the private repositories
  - name: basic-auth
    secret:
      secretName: "{{ git_auth_secret }}"
  - name: dockerconfig
    secret:
      secretName: regred
