---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: path-change-test
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main1]"
    #pipelinesascode.tekton.dev/on-cel-expression: |
      #event == "push" && ("components/?*/base/**".pathChanged())
spec:
  params:
    - name: repo_url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineSpec:
    params:
      - name: repo_url
      - name: revision
    tasks:
      - name: noop-task
        taskSpec:
          steps:
            - name: noop-task
              image: ubuntu
              script: |
                #! /bin/bash
                echo $(params.revision)
                echo $(params.repo_url)
                echo "************"
                sleep 20
                exit 0
